### PR TITLE
Alter include statements for local header files.

### PR DESCRIPTION
**Pull request by borfus**
While using Vim to edit a file while using the plugin "Syntastic", errors would appear showing that the plugin was unable to locate local header files.

This error occurs because the relative path was not fully used to include other subfolders in the `hag/src/` directory for each individual header file. While this change doesn't affect development or building, it should hopefully allow for easier editing with plugins like Syntastic that rely on the `#include` statements to located other files to help avoid compilation errors.

This pull request changes the include statements to include these sub-folders where necessary.

### CODE REVIEW

**Comment by JohnathonNow** [comment]
I considered changing the paths to be relative, but have been told this is considered bad practice.

I also use vim and syntastic, but I simply have my `C_INCLUDE_PATH` environmental variable set to contain each source directory within the project.

**Comment by borfus** [comment]
> I considered changing the paths to be relative, but have been told this is considered bad practice.
> 
> I also use vim and syntastic, but I simply have my `C_INCLUDE_PATH` environmental variable set to contain each source directory within the project.

Ah that's a good point I didn't know it was bad practice. I also didn't know you could set those manually in the `C_INCLUDE_PATH` file either, I'll have to take a look at that.

Just out of curiosity if you don't mind me asking, how does the project know where these header files are? Is this specified in the `MakeFile`? It's certainly cleaner to include just the names instead of the full relative path, and I'm curious because I think I'd like to try out this build method in the future.

**Comment by JohnathonNow** [comment]
The `Makefile` adds a `-I` flag to `gcc` for each each directory in the `src` directory. It's a bit of a hack, and there are definitely better ways to build projects, but for something this small it seemed fine.

**Comment by borfus** [comment]
Thanks a ton for the info! I'll go ahead and close this PR since grabbing the sources and headers inside the Makefile seems a lot more stable. I appreciate you spending time checking this out!
